name: clownfish-app
services:
- name: ds-bot
  github:
    repo: hizoo5/DS-Bot
    branch: main
  build_command: pip install -r requirements.txt
  run_command: python 788.py
  http_port: 8080
  envs:
  - key: PYTHONUNBUFFERED
    value: "1"
