name: clownfish-app
services:
- name: ds-bot
  github:
    repo: hizoo5/DS-Bot
    branch: main
  source_dir: DS-Bot
  build_command: pip install -r requirements.txt
  run_command: python 788.py
  resource_type: worker
  envs:
  - key: PYTHONUNBUFFERED
    value: "1"
