verbs = [
    "run", "jump", "hide", "sing", "dash", "flip", "dive", "code", "swim", "grind",
    "kick", "climb", "crawl", "shoot", "punch", "spin", "roll", "drift", "hike", "glide",
    "sprint", "slice", "zoom", "strike", "flow", "sneak", "blast", "snap", "race", "aim",
    "chant", "whip", "throw", "lurk", "crash", "build", "write", "erase", "draw", "solve",
    "chase", "guard", "leap", "bend", "split", "press", "forge", "melt", "track", "steal",
    "blink", "grasp", "shove", "hover", "fence", "tumble", "parry", "reflect", "absorb", "deflect",
    "ignite", "extend", "quiver", "shiver", "whirl", "flick", "pluck", "peck", "scrape", "polish",
    "shred", "whack", "combo", "juggle", "nudge", "topple", "vanish", "appear", "shatter", "repel",
    "inflate", "deflect", "project", "detect", "infect", "reject", "collect", "perfect", "reflect", "connect",
    "inject", "respect", "suspect", "neglect", "protect", "elect", "select", "correct", "redirect", "disconnect",
    "bounce", "carve", "dodge", "fling", "grapple", "hover", "impale", "joust", "knock", "lunge",
    "muffle", "nock", "outrun", "peel", "quicken", "ramble", "scurry", "trample", "unfold", "vault",
    "warp", "yank", "zap", "amble", "brawl", "crouch", "devour", "ensnare", "fumble", "gaze",
    "howl", "intercept", "jolt", "kindle", "lurch", "mimic", "nibble", "overpower", "pounce", "quake",
    "rally", "skulk", "thrash", "unleash", "veer", "wrestle", "yowl", "zest", "ascend", "burrow",
    "clutch", "demolish", "elude", "flicker", "glisten", "hurtle", "intrude", "jostle", "keel", "latch", 
    "ironfang", "pixelnova", "stormblade", "wraithwolf", "dragonstrike", "plazmashot",
    "darkember", "skywarrior", "vengeancex", "lunarfrost", "shadowthorn", "cryptik",
    "novafox", "stormbreaker", "rogueangel", "cyberskull", "wildcobra", "trickshotz",
    "raptorsoul", "flameviper", "quantumvoid", "neonwolf", "snipergod", "tornadoz",
    "phoenixrage", "carnagex", "rockzilla", "stormyboy", "venombite", "deathstrike",
    "voidmaster", "lunarknight", "whiteraven", "crimsonaxe", "sniperwolfx", "rapidflare",
    "oblivionking", "vortexlord", "hellhoundz", "icebreakerx", "ghostvenom", "toxicblast",
    "razorstorm", "feralnight", "wolfcryx", "shadowbladez", "infernodrake", "galacticrage",
    "stormfrost", "voidfang", "demonsnare", "ironphantom", "gravetide", "nightblazer",
    "titanwrath", "havoklord", "skullburn", "ravenlordz", "crimsonfury", "blastnova",
    "riftwalker", "snarefang", "thornblight", "nightvenom", "cyberflare", "stormfangz",
    "novaorbit", "toxicrage", "phantomflare", "razorfangx", "shadowflamez", "ghoulvenom",
    "nightnova", "burningvoid", "raptorflare", "stormrazor", "snarlfang", "warcryz",
    "phantomvoid", "lunarstrike", "novaember", "scarblade", "toxicfangz", "deathflare",
    "warzonex", "venomflare", "cybernova", "vortexfang", "thunderflare", "blastfangz",
    "soulburnz", "shadowrazor", "toxicnova", "stormrazorz", "ironflamez", "razorflarez",
    "voidnova", "flamecry", "lunarfangz", "emberflare", "shadowcryz", "phantomnova",
    "darknova", "stormblastz", "toxiccry", "novaflarez", "flarefang", "warfangz",
    "burnflare", "cyberflarez", "ironflarez", "novaorbitz", "shadowflarez", "snareflame",
    "flarecry", "toxicorbit", "blastcry", "novaorbitx", "flarevoid", "stormorbit",
    "flarephantom", "toxicorbitz", "cryflarez", "flarehound", "cybervoid", "stormvoidz",
    "novaorbitxx", "flarehoundz", "warflare", "burnnova", "shadoworbit", "stormcryz",
    "novaorbitzz", "phantomflarez", "flarevenom", "stormflarezz", "orbitflare", "cryvenom",
    "flarerage", "orbitnova", "flarephantomz", "stormorbitzz", "cyberorbit", "flareburn",
    "orbitflame", "cryflarezz", "flareblast", "stormcryxx", "novaorbitv", "phantomcryz",
    "orbitflarez", "flarehoundzz", "stormorbitv", "toxicflarez", "flareblaze", "orbitvenom",
    "cryblaze", "flarecyber", "stormflarev", "novaorbitq", "flarewolf", "stormcyber",
    "orbitblast", "flareking", "phantomorbit", "flaretoxic", "orbitflarev", "flarehoundv",
    "toxiccryz", "flarequeen", "stormflareq", "orbitnovaq", "flaredemon", "stormcryv",
    "cyberflareq", "orbitblastz", "flareghost", "stormorbitq", "cryphantom", "novaorbitp",
    "flarewitch", "stormflarep", "orbitcry", "flareraptor", "stormcryq", "orbitblaze",
    "flarevenge", "stormblazez", "cybercryz", "orbitvengez", "flarehaze", "stormphantom",
    "orbitflarep", "flarevoidz", "stormvenge", "orbitking", "flarelord", "stormlordz",
    "cyberlordz", "flarephantomx", "orbitqueen", "stormhaze", "flarehunter", "orbitstorm",
    "flarehunterz", "stormhunter", "orbitnovao", "flaremaster", "stormflareo", "phantomhaze",
    "orbitflareo", "flarelegend", "stormlegendz", "orbitflamez", "flarevenomx", "stormflamez",
    "orbitcryz", "flarechaos", "stormchaosz", 
    "PixelNomad", "CactusStrike", "BananaSlamma", "MoltenEdge", "TacoSlayer",
    "StormBringerX", "EchoBlast", "VortexSnipez", "ChurroLoco", "InfernoBeast",
    "AquaPhantom", "SteelBunny", "GigaNova", "TurboKoi", "SniperGuapo",
    "CocoNinja", "TornadoRider", "SavageKomodo", "TamalitoKing", "DuskHawk",
    "LunoxLegend", "RaptorShade", "ZenShooter", "VoltzRush", "NekoRider",
    "DragonSpade", "CruzitoX", "ReaperLynx", "TigreNegro", "ShadowTurtle",
    "Wolfito", "ThunderValk", "BladeMango", "MolinoStrike", "SlayerPinoy",
    "ChocoBandit", "ValorPunk", "KaijuSkull", "LocoSniper", "CyberGoat",
    "RavenousSun", "PantherByte", "SombraWolf", "TropaKing", "ZetaBolt",
    "MadreVibes", "TideCrusher", "OroHunter", "SniperDiablo", "QuakeScorpion",
    "VenenoFang", "BlitzVandal", "SirenaEdge", "NoobitoMax", "RapidMako",
    "NitroLag", "LagDestroyer", "CodexVibe", "VandalCore", "OmegaSloth",
    "ZombieFiesta", "ManokWarrior", "TortillaShot", "Dragoncito", "MayaStrike",
    "HawkDrift", "ValorSnakes", "ElDinamico", "BlitzTsunami", "QuantumCruz",
    "DarkPixelz", "FuegoSniper", "NinjaPilipino", "StormWaffle", "RapidHusky",
    "LunoxStorm", "OnyxSerpent", "CyberPhantom", "TigreFuego", "MysticLuz",
    "SombraLynx", "LethalOtter", "SolarJaguar", "PinoyHammer", "TurboIglesia",
    "ShadowMole", "ZapDragon", "TacoKnight", "VoltzHero", "LagunaSniper",
    "OmegaPanda", "ElectroBandido", "StormLobster", "SavageKubo", "OrcaBlade",
    "PixelShark", "TurboVandal", "BlitzRider", "PhantomSun", "FrostedLynx",
    "BarrioSniper", "HawkLagoon", "RazorKomodo", "BananaRiot", "FuegoClaw",
    "ValorLocust", "ZyraNox", "MoltenShadow", "TropaSniper", "NekoStorm",
    "PinoyFrost", "ArcadeSlasher", "DriftCobra", "MangoBlazer", "DotaKid",
    "BaryoHunter", "PhantomVolt", "LagSwitchX", "WildTaco", "ToroSavage",
    "ShadowFiesta", "LocoPunk", "ElectricKomodo", "TideJaguar", "ValorLag",
    "SniperTamal", "NovaCoyote", "StormLocust", "PantherZero", "NeonTigre",
    "TropaShadow", "CruzitaVibes", "SavageOtter", "ZetaTiger", "BarrioBeast",
    "KoiPhantom", "OmegaShark", "VoltJaguar", "ShadowTamal", "DragonLagoon",
    "PixelFrost", "ElRayoX", "MadreStorm", "KomodoZero", "SniperGato",
    "FuegoPanther", "TurboWaffle", "OnyxBarrio", "MangoShadow", "SavageTurtle",
    "DriftMole", "OrcaRider", "HuskyVolt", "ChurroStorm", "LagBeast",
    "WolfZero", "QuantumOtter", "ValorVolt", "TidePixel", "SombraFiesta",
    "ShadowManok", "NeonPunk", "BarrioVolt", "SniperOrca", "DragonFrost",
    "InfernoLoco", "ToroLagoon", "PixelOtter", "ThunderLocust", "NovaShadow",
    "CruzitoVolt", "TurboKomodo", "ValorOtter", "PhantomJaguar", "LagLynx",
    "CyberBarrio", "PantherFrost", "StormOtter", "WolfFuego", "NekoJaguar",
    "PixelStorm", "SavageLagoon", "ShadowRider", "BlitzOtter", "MangoVolt",
    "LynxFiesta", "TurboTiger", "DragonPixel", "PhantomOtter", "ZetaLocust",
    "KomodoLag", "ShadowVolt", "InfernoOtter", "VoltFiesta", "SavageVolt",
    "OrcaVolt", "ValorJaguar", "LagOtter", "TurboLagoon", "PantherVolt",
    "strafe", "parry", "block", "counter", "evade", "riposte", "feint", "taunt",
    "summon", "banish", "curse", "bless", "heal", "revive", "stun", "silence",
    "freeze", "burn", "shock", "poison", "blind", "root", "snare", "slow",
    "hasten", "fortify", "weaken", "empower", "drain", "siphon", "leech", "channel",
    "cast", "invoke", "conjure", "dispel", "purge", "cleanse", "shield", "barrier",
    "smash", "crush", "pound", "slam", "bash", "wallop", "pummel", "batter",
    "pierce", "stab", "impale", "skewer", "thrust", "jab", "lunge", "charge",
    "ambush", "flank", "retreat", "advance", "regroup", "rally", "defend", "assault",
    "scout", "survey", "patrol", "guard", "watch", "monitor", "observe", "spy",
    "hack", "breach", "infiltrate", "sabotage", "disrupt", "jam", "override", "decrypt",
    "encode", "transmit", "receive", "scan", "analyze", "compute", "process", "execute",
    "compile", "debug", "optimize", "upgrade", "enhance", "modify", "customize", "configure",
    "deploy", "launch", "activate", "initialize", "terminate", "shutdown", "reboot", "restart",
    "backup", "restore", "save", "load", "export", "import", "sync", "transfer",
    "morph", "shift", "transform", "evolve", "mutate", "adapt", "regenerate", "resurrect",
    "phase", "teleport", "blink", "dash", "rush", "blitz", "surge", "burst",
    "channel", "focus", "concentrate", "meditate", "pray", "worship", "sacrifice", "offer",
    "trade", "barter", "exchange", "purchase", "sell", "auction", "bid", "gamble",
    "negotiate", "persuade", "convince", "bribe", "threaten", "intimidate", "coerce", "manipulate",
    "deceive", "trick", "fool", "mislead", "distract", "confuse", "bewilder", "daze",
    "CrankedGod", "BuildKingTTV", "EditMaster", "BoxFighterPro", "WKeyWarrior",
    "NinjaLite", "TwitchRival", "CrankMachine", "TrapperElite", "PumpShotty",
    "ChugJugChamp", "StormScout", "VictoryHunter", "BushCamper", "NoobTuber",
    "OpLooter", "TiltedKing", "SquadWiper", "SniperNest", "BuildBattler",
    "RadiantAce", "IronImmo", "FlashBang", "SageWall", "JettDasher",
    "ReynaFrag", "OmenTP", "ViperToxic", "CypherCam", "SovaArrow",
    "PhantomFiend", "VandalViper", "OperatorMain", "EcoFrag", "PistolRound",
    "ClutchKing", "RetakeGod", "PlantSpike", "DefuseHero", "AceHunter",
    "FrancoMain", "GordKill", "AlucardLord", "LancelotSpeed", "FannyGod",
    "HayabusaX", "GusionPro", "GrangerSnipe", "KaguraMain", "EsmeraldaCC",
    "ChouKing", "KhaleedDash", "YveTech", "PaquitoFist", "BeatrixGun",
    "BrodyShot", "WanwanBounce", "ClintBullet", "KarinaAssassin", "HelcurtShadow",
    "BaneBuff", "JohnsonCar", "TigrealTank", "KhufraCC", "GatotKaja",

]

nouns = [
    "wolf", "lion", "eagle", "tiger", "panda", "ninja", "ghost", "robot", "pixel", "dragon",
    "phoenix", "otter", "rhino", "falcon", "sparrow", "panther", "cobra", "shark", "orca", "whale",
    "hawk", "raven", "viper", "lynx", "bear", "moth", "storm", "ember", "shadow", "flame",
    "stone", "river", "cloud", "frost", "leaf", "branch", "wave", "wind", "echo", "blaze",
    "comet", "vortex", "nebula", "quasar", "pulse", "nova", "orbit", "crater", "lunar", "solar",
    "ember", "frost", "thunder", "light", "void", "mirror", "crystal", "golem", "sphinx", "wraith",
    "specter", "banshee", "gargoyle", "centaur", "griffin", "kraken", "basilisk", "chimera", "harpy", "pegasus",
    "serpent", "wizard", "archer", "knight", "samurai", "viking", "pirate", "sorcer", "monk", "cleric",
    "rogue", "assassin", "berserk", "paladin", "warlock", "shaman", "alchemist", "engineer", "mechanic", "scientist",
    "astronaut", "detective", "explorer", "inventor", "merchant", "prophet", "scout", "traveler", "watcher", "zealot",
    "dagger", "shield", "hammer", "scythe", "arrow", "blade", "cannon", "dagger", "flail", "gauntlet",
    "halberd", "javelin", "katana", "lance", "mace", "nunchaku", "rapier", "saber", "trident", "whip",
    "artifact", "grimoire", "potion", "rune", "scroll", "tome", "amulet", "crown", "diadem", "orb",
    "scepter", "torch", "veil", "cloak", "mask", "helm", "greaves", "plating", "sigil", "totem",
    "citadel", "dungeon", "fortress", "labyrinth", "monolith", "nexus", "obelisk", "pyramid", "sanctum", "tower",
    "volcano", "waterfall", "cavern", "chasm", "grotto", "marsh", "meadow", "tundra", "badlands", "fjord", 
    "NeonDagger", "PixelFalcon", "ShadowRogue", "ToxicAngel", "RebelWolf",
    "ViperHex", "ChocoBoi", "FiestaLoco", "TurboSkull", "FrostLynx",
    "BlazeHawk", "JungleCreep", "CritShot", "SamuraiEdge", "Sn1p3King",
    "LapuLapuPH", "ValorHex", "DriftFox", "GunnerMax", "HoloSniper",
    "StealthVibe", "ThunderZ", "SpicyRamen", "GuerreroX", "TricksterPH",
    "PixelCobra", "BotHunter", "MetaMage", "LagSwitch", "PinoyWarrior",
    "TrollZilla", "AquaBlast", "TacoRider", "ToxicRush", "WolfGang",
    "CyberKat", "ShurikenZ", "BrawlerPH", "FlameGhost", "DarkTaco",
    "FiestaSlang", "TankLord", "JungleKing", "RushShot", "MetaFlex",
    "NekoByte", "Sn1perino", "PsychoHawk", "DragonClash", "ValorSniper",
    "TurboZero", "TropaKing", "CrazyHex", "BotHunterX", "ShadowEdge",
    "FuegoMax", "RapidWolf", "LagGod", "IceKat", "GigaShot",
    "MysticTroll", "StormRage", "CervezaKing", "KillerByte", "SneakyLynx",
    "TropaLegit", "CyberFiesta", "NoMercyPH", "SavageShot", "DaggerHex",
    "ValorBot", "MobileSlayer", "FragZilla", "GhostByte", "SamuraiLynx",
    "FuegoWolf", "ArcaneLord", "MetaBlade", "FlameZero", "TropaEdge",
    "CyberShot", "PinoySniper", "RogueTaco", "TurboMage", "CritKat",
    "DarkByte", "ShadowWolfX", "SneakyFox", "VortexTroll", "TropaLegends",
    "LynxEdge", "PixelHunter", "ValorTropa", "DriftGhost", "TankZero",
    "ToxicRushX", "ShurikenMax", "LagHunter", "SpicyTaco", "PinoyFlex",
    "FuegoSniper", "RapidTroll", "SamuraiShot", "MetaZero", "DarkWolfZ",
    "RogueByte", "FlameHunter", "SneakyShot", "TurboGhost", "LagZilla",
    "ValorLynx", "SavageBot", "FiestaShot", "CritWolf", "BotRogue",
    "NekoHunter", "DragonZero", "FuegoEdge", "ArcaneSniper", "TropaGod",
    "ShadowKat", "PinoyBlast", "MysticWolf", "CrazyShot", "LagMage",
    "VortexWolf", "MobileByte", "TurboSn1per", "RogueLord", "MetaRush",
    "ToxicFox", "RapidHunter", "SamuraiZero", "CyberRogue", "SavageHex",
    "TropaMage", "ValorBlade", "BlazeZero", "ShadowByte", "SneakyWolf",
    "FragHunter", "IceSniper", "TankLynx", "DragonLord", "LagShot",
    "ArcaneEdge", "FiestaWolf", "TurboBlast", "PixelZero", "TropaSn1per",
    "FuegoGhost", "DarkRush", "MetaHunter", "SamuraiGhost", "LagBlade",
    "RogueHex", "ToxicLynx", "CyberWolf", "RapidByte", "SavageEdge",
    "NekoTroll", "ShadowLord", "DragonMage", "FiestaHunter", "MobileEdge",
    "LagWolf", "SneakyBlast", "TurboEdge", "FlameRush", "PixelHunterX",
    "CritLord", "RogueWolf", "ArcaneBlast", "ValorRush", "DarkEdge",
    "TropaShot", "ShadowFlex", "TankBot", "DragonHunter", "SneakyHex",
    "LagFlex", "TurboWolf", "RapidMage", "FiestaRush", "SamuraiEdgeX",
    "MysticByte", "MobileGhost", "ValorHunter", "TropaZero", "ShadowSn1per",
    "FlameTroll", "BotBlast", "SavageWolf", "TurboLynx", "LagHunterX",
    "PixelBlast", "FuegoMage", "CritRush", "SamuraiHunter", "FiestaMage", 
    "blazeOath", "shadowCircuit", "toxicMango", "neonWolfie", "gigaFrost",
    "valorCrush", "echoWarden", "pixelVenom", "stormPhantom", "novaRider",
    "gamerTropa", "axeSerpent", "kappaBurst", "mysticLobster", "retroBoom",
    "luchaTiger", "codeFang", "lunarBlade", "driftOmen", "spikeShadow",
    "kometaRush", "xenoSkull", "battleChoco", "duendeKing", "toxicAlma",
    "cryptoSlang", "valorRogue", "ravenQuest", "digiVortex", "dotaPriest",
    "legendaryHawk", "fragSoul", "rayoSmash", "slangMyst", "cosmoByte",
    "shadowLynx", "kaboomFiesta", "arcaneValor", "savageRooster", "urbanKraken",
    "blitzOrca", "pinoyPogi", "necroWing", "wildAztec", "midnightCobra",
    "latinaQueen", "maskHunter", "novaRogue", "sigmaFox", "locoBlast",
    "quakeDroid", "saltyShark", "manilaVibe", "voodooStrike", "stormyToad",
    "pinoyLegend", "moltenFang", "silentToro", "rapidScorpion", "technoZyra",
    "barrioLord", "astroLeech", "vengeDagger", "urbanMako", "madReactor",
    "spicyVolcano", "quakeTalon", "bloodedTiger", "valorHawk", "toxicCactus",
    "desertFang", "nightFalco", "luchaVeneno", "elNavaja", "stormTroca",
    "pinoyFury", "jungleHex", "valorKoi", "matrixBlade", "fatalDune",
    "lunarMage", "novaFrog", "quakeLion", "toxicVibe", "sigmaHound",
    "rageOmen", "frostSoul", "driftClaw", "ligawWolf", "pinoySama",
    "venenoRage", "quakeDragon", "urbanLag", "savageGhost", "fiestaByte",
    "digiWolf", "urbanFangs", "stormAzul", "valorChoke", "fatalAlto",
    "battleSloth", "arcaneJelly", "riotSerpent", "novaSkies", "fiestaXtreme",
    "jungleOath", "crazyMantis", "valorNox", "toxicVortex", "ravenGato",
    "aztecByte", "pinoyLaro", "stormKai", "urbanFuego", "driftMaya",
    "valorLobster", "lunarAtom", "viciousCrab", "matrixGorilla", "fatalBuzz",
    "omegaBlast", "novaSpirit", "quakeSpider", "cyberTropa", "voodooByte",
    "blitzGecko", "aztecVibe", "manilaWarden", "urbanSpectre", "rageAtom",
    "shadowOx", "luchaPhantom", "moltenSkull", "valkBomba", "stormWidow",
    "pinoySlam", "legendRooster", "venenoByte", "novaValor", "quakeKoi",
    "toxicByte", "manilaStrike", "driftSamurai", "spicyWolf", "cyberGato",
    "valorHex", "luchaShadow", "crazyBoi", "aztecSoul", "voodooCrash",
    "stormAzulon", "bloodedMantis", "rayoFiesta", "riotLag", "novaLagoon",
    "blitzBoomer", "urbanFangz", "moltenScorpio", "frostOwl", "fatalVeneno",
    "elDragon", "pinoyTigre", "valorSpawn", "quakeToro", "cyberHound",
    "urbanCrush", "ravenByte", "stormLing", "voodooCore", "madGator",
    "novaBoom", "pinoyReyes", "blazeCobra", "sigmaStrike", "valorByte",
    "moltenOx", "battleNox", "crazyPanda", "urbanKnight", "spikeLag",
    "shadowBarrio", "novaZero", "luchaRage", "stormPhantomz", "toxicSkies",
    "pinoyWarlord", "rayoWolf", "valorFiesta", "aztecTide", "blitzAtom",
    "driftKappa", "crazyCobra", "matrixRaven", "stormDraco", "frostToro",
    "fatalSama", "pinoyCrush", "novaHound", "rayoDragon", "urbanBoom",
    "cyberBomba", "valorLynx", "quakeRogue", "moltenByte", "blitzRaptor",
    "pinoyHex", "stormLagoon", "frostLobster", "riotToad", "shadowSoul",
    "urbanWolfie", "valorKingz", "novaSpectra", "battleJaguar", "driftByte",
    "cyclone", "tsunami", "avalanche", "earthquake", "blizzard", "typhoon", "hurricane", "tornado",
    "meteor", "asteroid", "galaxy", "cosmos", "universe", "dimension", "realm", "plane",
    "abyss", "void", "chasm", "rift", "portal", "gateway", "nexus", "core",
    "sentinel", "guardian", "protector", "defender", "champion", "hero", "warrior", "fighter",
    "mage", "warlock", "sorcerer", "enchanter", "wizard", "witch", "druid", "priest",
    "ranger", "hunter", "tracker", "scout", "spy", "agent", "operative", "mercenary",
    "gladiator", "duelist", "champion", "contender", "rival", "nemesis", "adversary", "foe",
    "kraken", "leviathan", "behemoth", "titan", "colossus", "juggernaut", "goliath", "giant",
    "specter", "phantom", "apparition", "poltergeist", "demon", "devil", "fiend", "daemon",
    "seraph", "angel", "celestial", "divine", "immortal", "eternal", "ancient", "primordial",
    "relic", "artifact", "treasure", "heirloom", "legacy", "memorial", "monument", "shrine",
    "temple", "cathedral", "chapel", "monastery", "sanctuary", "haven", "refuge", "shelter",
    "arsenal", "armory", "forge", "foundry", "workshop", "laboratory", "facility", "compound",
    "outpost", "stronghold", "bastion", "rampart", "bulwark", "garrison", "barracks", "camp",
    "ravine", "canyon", "gorge", "valley", "plateau", "mesa", "butte", "cliff",
    "reef", "atoll", "lagoon", "bay", "cove", "harbor", "port", "dock",
    "glacier", "iceberg", "tundra", "taiga", "steppe", "savanna", "prairie", "desert",
    "jungle", "rainforest", "woodland", "grove", "thicket", "copse", "glade", "clearing",
    "summit", "peak", "crest", "ridge", "slope", "hillside", "foothill", "mountaintop",
    "talon", "claw", "fang", "horn", "tusk", "spike", "barb", "quill",
    "BelerickTree", "LolitaTank", "UrgotMain", "RafealaShield", "HylosTank",
    "PudgeHook", "InvokerCombo", "PhantomSplit", "TinkerSpam", "RubickSteal",
    "WindRanger", "SFRaze", "MorphReplicate", "AntiMageTP", "SlarkLeap",
    "MiranaArrow", "EarthSpike", "ZeusLightning", "LionFinger", "LinaStun",
    "SnipAssassin", "DrowRanger", "CrystalSupport", "OmniHeal", "OracleRoot",
    "TechiesMine", "BountyTrack", "RikiInvis", "ClinkzFire", "TempAssassin",
    "LanxiangPro", "YunzhongMain", "DaQiaoPort", "YuanGeTele", "LubanSnipe",
    "HouYiStun", "SunCeHook", "YaoCling", "MiYueVamp", "ZhangFeiTank",
    "GuanYuSpin", "LiuBeiClone", "DiaochanCharm", "ZhugeStun", "XiaoQiaoSlowmo",
    "AthenaTaunt", "GeminiStun", "MayaUlt", "AoXinDrag", "BiYuetanAss",
    "YassuoWind", "ZedShadow", "LeeSinKick", "ThreshHook", "BlitzGrab",
    "DariusDunk", "GarenSpin", "LuxLaser", "AhriCharm", "KatarinaR",
    "VayneRoll", "JhinSnipe", "JinxRocket", "CaitlynTrap", "AsheArrow",
    "MasterYiQ", "RengarJump", "KhaZixEvo", "RivenCombo", "FioraDash",
    "SyndraStun", "OriannaUlt", "TalonParkour", "EkkoRewind", "AkaliFLip",
    "AWPGodCS", "AK47Spray", "M4A1Tap", "DesertEagle", "DualiesRun",
    "NadeKing", "FlashBanged", "SmokeGod", "MollyToss", "HeadshotOnly",
    "RushBPlayer", "CampCorner", "EcoWarrior", "ForceRound", "FullBuyGod",
    "LongHold", "ShortRush", "MidControl", "CatWatch", "WindowPeek",
]

intl_names = [
    "akira", "marco", "sven", "yuki", "diego", "leon", "ivan", "sofia", "liam",
    "hans", "luca", "noah", "kai", "hana", "nora", "elena", "isla", "rosa",
    "zara", "arun", "mei", "tomo", "hiro", "ethan", "jules", "niko",
    "ivana", "angelo", "franz", "layla", "dario", "johan", "elias", "mira",
    "sasha", "viktor", "zelda", "bella", "carlo", "dante", "esme",
    "freya", "gunnar", "helga", "igor", "juno", "kato", "lina", "milo", "nadia", "oskar",
    "petra", "quinn", "radek", "sana", "tova", "ulla", "vega", "willem", "xenia", "yara",
    "zoran", "aiko", "bjorn", "cleo", "dmitri", "elio", "gita", "ida",
    "jasper", "kaja", "lazar", "maja", "nikol", "olga", "pavel", "quan", "runa", "sorin",
    "tilda", "udo", "valda", "wolf", "ximena", "zola", "anton", "briar", "cyril",
    "elma", "fionn", "gerd", "indra", "jarek", "kamil", "leif", "misha",
    "pia", "renata", "stig", "ulla", "viggo", "wanda",
    "xander", "yevgen", "anders", "bodil", "caius", "dagna", "erik", "frida", "gunn",
    "hedda", "ivo", "jolan", "kirst", "lars", "maren", "nils", "ola", "peder", "ragna",
    "sigrid", "torsten", "ulf", "viveka", "walter", "yngve", "zenta", "aaron", "britta", "casmir",
    "dagny", "ebba", "flemming", "grethe", "harald", "inge", "jorn", "klara", "loke", "magnus",
    "nanna", "odd", "pernille", "rasmus", "sif", "torkel", "valter", "yrsa", "zephyr", "agnar",
    "berit", "cato", "dorte", "einar", "frode", "gyda", "halvor", "irma", "jette", "keld",
    "lilli", "mogens", "nynne", "ole", "povl", "rune", "sanne", "tove", "ulla", "vagn",
    "yngvar", "zita", "ShadowWolf", "DragonSlayer99", "ArcaneKnight", "StormBreaker", "GhostHunter", "ValorAce",
    "MysticRaven", "IronFist", "BlazeFury", "NightCrawler", "CrimsonViper", "SteelTitan",
    "AquaPhoenix", "SilentSniper", "RogueSamurai", "DarkReaper", "FrostByte", "ThunderClaw",
    "VenomStrike", "ShadowNinja", "StormChaser", "ChaosLord", "InfernoKing", "LoneWolf",
    "SilverBullet", "RagingBull", "CyberPunked", "AtomicStorm", "Sn1perElite", "TropaKing",
    "BarrioLord", "GandaQueen", "PinoyPride", "TropaBoyz", "LakasMo", "BarkadaCrew",
    "CholoRider", "VatoLoko", "FiestaKing", "AmigoLoco", "BandidoX", "CorazonFuego",
    "ElToro", "LaVidaLoca", "SombreroGang", "GuapoBoss", "HermanoX", "CervezaKing",
    "ElRey", "CabronX", "TacoLover", "CarneAsada", "GalloRojo", "SalsaFiesta",
    "EspadaFuego", "GuerraLoco", "DiabloRojo", "CorazonLoco", "AzulDragon", "Tormenta",
    "BatangKalye", "AstigBoy", "GwapoBoss", "JeproxX", "Rakista", "TambayKing",
    "KantoGang", "TrapoLoco", "GagoBoy", "TropaBida", "AstigMo", "LokoLoko",
    "MLBBKing", "LegendsNeverDie", "ChooxArmy", "AkosiDogie", "OhebTime", "WisePlays",
    "MobaLegend", "BangBangPro", "EsmeraldaMain", "FrancoHook", "LancelotGod", "AlucardX",
    "CODKiller", "HeadshotKing", "Sn1perDown", "NoScopePro", "WarzoneBoss", "RogueOps",
    "ValorantAce", "SpikeDefuser", "PhantomShot", "VandalPro", "JettDash", "SageHeal",
    "LoLKing", "PentakillX", "BaronStealer", "DariusDunk", "LuxLaser", "YasuoWind",
    "DotaGod", "InvokerPro", "PudgeHook", "MiranaArrow", "SlarkThief", "TechiesBoom",
    "HOKMaster", "ArenaKing", "AOVPro", "FrostMage", "DragonLancer", "ShadowKnight",
    "MobileWarrior", "ConsoleBeast", "PCMaster", "LANLord", "ArcadeKing", "PixelHero",
    "CyberSamurai", "NeoShadow", "MatrixHunter", "GlitchBoss", "HackStorm", "DataGhost",
    "StormDragon", "HellKnight", "BloodHunter", "BoneCrusher", "DarkSlayer", "RageMaster",
    "FireLord", "IceWizard", "WindRider", "EarthShaker", "OceanKing", "SkyBreaker",
    "ShadowFox", "IronClaw", "SteelRider", "WildTiger", "JungleBeast", "SavageBear",
    "TropaBoy", "PinoyWarrior", "TagalogKing", "AstigMoTo", "GwapoMo", "TambayMo",
    "FiestaBoy", "PandesalKing", "AdoboMaster", "LumpiaBoss", "SisigPro", "HaloHaloX",
    "ElMatador", "SalsaKing", "VivaMexico", "TacoGang", "LuchadorX", "GuerreroRojo",
    "SombreroX", "FiestaMo", "AztecaKing", "MayaBoss", "DiabloX", "CorazonRojo",
    "RapidFire", "IronStorm", "DeathDealer", "NightRider", "StormWolf", "InfernoX",
    "TropaAstig", "PinoyLegend", "GagoMo", "GwapoX", "KantoBoy", "TambayAstig",
    "BarkadaMo", "TropaX", "BoyKalye", "PogiBoss", "AstigPogi", "LokoX",
    "PhantomLord", "SoulReaper", "FrostDragon", "FireStorm", "ShadowKing", "DarkKnight",
    "ThunderWolf", "IronDragon", "StormBreakerX", "GhostKiller", "CyberWolf", "NeoDragon",
    "PixelSlayer", "RetroHero", "ConsoleKing", "LanWarrior", "MobileSlayer", "PCBeast",
    "AlphaWolf", "OmegaKnight", "ZetaHunter", "SigmaBoss", "DeltaForce", "BetaSlayer",
    "SkyRider", "StarBreaker", "LunaShadow", "SolarFlare", "NovaBlast", "CometX",
    "AstroKing", "CosmoWarrior", "GalaxyHero", "NebulaKnight", "MeteorStorm", "OrbitX", 
    "ironhawk42", "mysticwolf", "papichulo23", "ligawnaaso", "xXValorXx", "torero98",
    "skullcrusher11", "pinoypride08", "guerreroMX", "aninoMaster", "stormfang", "dragonlady",
    "reaperlord", "tropaGang", "panadero23", "lagartija", "wildboar66", "shadowhunter",
    "sniperqueen", "kabalyeroPH", "travesura", "aztecaMX", "doombringer", "lostsoul99",
    "noobmaster44", "magitingWarrior", "espadaLuz", "nightcrawlerX", "gatillero", "manananggal",
    "samuraiGhost", "badboi07", "corazonFuego", "pinaySlayer", "panikiLord", "dragonscale",
    "barrioKing", "underdog27", "lagLagLover", "tormentaRoja", "snakelord", "butanding",
    "basurero101", "kabogKing", "fireblade", "phantomz", "bigote69", "callejero23",
    "arkanghel", "scorpionX", "torogamer", "gunman44", "slypanther", "ligerPower",
    "tiyagaBoy", "ninjutsu", "triggerman", "luchador77", "azucena", "shadowKing",
    "lambanogLord", "tigreOscuro", "spitfire99", "voodooman", "barako88", "pogiBoy",
    "stormbringer", "hustla24", "pirataRojo", "killerbeeX", "baleteGhost", "tigreBlanco",
    "reynadeoro", "barbaro", "vandalKing", "serpienteMX", "guerillaBoy", "duendeSlayer",
    "mrClutch23", "ignitionX", "sombraNegra", "senyorito", "kalabawPower", "anacondaLord",
    "papasito98", "pistolero23", "valkyrieX", "wolfgang77", "kabalyeraPH", "demonChild",
    "heroicSoul", "urbanHunter", "trapoKing", "ninjaboi22", "manggangHilaw", "terremoto",
    "devildog", "malakasPH", "pinayqueen", "swordmaster", "tigreRojo", "barakoKing",
    "wildrider", "aztecWarrior", "kantoBoy23", "triplekillX", "drakonlord", "supremo",
    "carabaoKing", "guapoBoi", "blackmage", "gunlord77", "espirituRojo", "bakunawaPH",
    "mambaBlack", "guerrillaMX", "firestormX", "skaterPinoy", "killerinstinct", "panaderoPH",
    "rebelboy23", "shadowfang", "kabogPH", "aztecSpirit", "manloloko", "streetlord",
    "wolfheart", "gatlingX", "pandaSlayer", "sorpresa77", "legendkiller", "tagaBaryo",
    "scavengerX", "butandingBoy", "ligeroSoul", "kapatidMo", "dragonheart", "pinayFierce",
    "wildShadow", "ragnarok77", "kalyeKing", "giganteMX", "luzOscura", "veneno88",
    "skullLord", "espadaMX", "senyorGang", "swordbreaker", "demonyoPH", "chismoso",
    "misterioso", "gunnerX", "palabanPH", "aztecRey", "ghettoKing", "hustlerPH",
    "labanHero", "elToro", "reyNegro", "kantoSlayer", "labananPH", "manongBoy",
    "wolfpack99", "pinayWarrior", "dragonrider", "mambaKing", "escorpion", "killerSoul",
    "tropaBoy", "samuraiShadow", "matador23", "espirituX", "kabogGang", "panikiX",
    "pinoyHunter", "reynaMX", "spartan77", "sniperX", "baranggayBoss", "terorista",
    "gunlordPH", "swordX", "luchadorNegro", "manliligaw", "labanKing", "aswangHunter",
    "kabalyeroX", "dragoonMaster", "espadaOscura", "vengefulSoul", "barakoPH", "lagimBoy",
    "stormchaser", "sagisagPH", "guerrillaX", "aztecShadow", "ligawGang", "madrider",
    "kalasagPH", "underdogPH", "streetFighter", "shadowRogue", "tropaKing", "labanero",
    "barrioSoul", "dagaBoy", "kabayoLord", "wildhunter", "ghettoX", "magitingPH", 
    "ReyKiller", "ShadowDancer", "CrispyHalo", "ZetaWolf", "InfernoPulse", "ToxicShot",
    "GringoLoco", "BalutKing", "HadesViper", "TropaBoy", "WildStag", "PandaRider",
    "ValorEdge", "TropaLad", "ElBrujo", "NexusWarden", "SabongWarrior", "TurboFox",
    "CholoSwag", "BarrioGhost", "TropaNinja", "OmegaCrow", "QuickZ", "DracoFire",
    "PistonHead", "Bruhito", "ElCrack", "NeonJunkie", "KatipunanX", "AztecLad",
    "BarrioNinja", "ShinigamiX", "BangusLord", "ChaosSlayer", "TurboPanther", "CobraFang",
    "SkyReaper", "LaVidaLoco", "ShadowPinoy", "BrawlerKing", "TrapoBoy", "RiftHunter",
    "VoltzX", "TropaSniper", "GigaWolf", "BarrioGamer", "LocoLegend", "NekoShadow",
    "InfernalDog", "TropaKing", "RebelWraith", "BlazeHornet", "CactusJack", "Brozoid",
    "LunoxDream", "PinoyX", "MysticCrow", "TorqueX", "FuegoKid", "ElCapo",
    "MadHitter", "BarrioSamurai", "ZephyrWolf", "JadeTiger", "SniperZero", "TurboRage",
    "BoomPinoy", "Salvaje", "MegaWarlord", "ShurikenBoy", "SpicySabong", "ViperZero",
    "RumbleBeast", "ElDragon", "TropaRogue", "BarrioLegit", "QuakeLord", "PogiBoy",
    "ElGhost", "BangBangKid", "LaMuerte", "SavageCrow", "InfernoZero", "ElCazador",
    "WreckingPinoy", "RiftBrawler", "TropaLord", "PhantomG", "TurboWolf", "FiestaKing",
    "KalyeBoy", "ShadowAztec", "GagoLoco", "ChaosGhost", "NightSabong", "ElNinja",
    "SavageWolf", "TropaBruh", "BarrioTiger", "DarkHornet", "ZapataKid", "BrozLord",
    "LunoxZero", "TorqueWolf", "BarrioBrujo", "MegaShadow", "TurboSamurai", "NekoKid",
    "TropaCrow", "BarrioSniper", "SavageDragon", "ElLocura", "ChaosKing", "WildHornet",
    "InfernalRage", "LocoBruh", "FiestaGhost", "TurboDragon", "ShadowKid", "MegaViper",
    "KalyeSavage", "JadeCrow", "NekoBrujo", "BarrioKing", "ZetaTiger", "TurboLegit",
    "TropaBeast", "PhantomLord", "CactusZero", "OmegaPinoy", "NightKid", "SavageSamurai",
    "RebelDragon", "BrozSavage", "LaBruja", "LocoShadow", "DarkWolfX", "TorqueDragon",
    "FiestaWarrior", "TropaZero", "BarrioBruhito", "MysticLord", "BangBangZero", "WildBrujo",
    "RumbleDragon", "KalyeSavageX", "PhantomTiger", "MegaGhost", "TropaSavage", "ElPinoy",
    "ShadowRogue", "TurboKid", "BarrioCrow", "LunoxKing", "ZapataGhost", "ChaosTiger",
    "InfernalSavage", "DarkCrow", "BoomDragon", "SavageLord", "KalyeBrujo", "ShadowBruh",
    "TurboFiesta", "BarrioLegendX", "WildCrow", "LaBestia", "PhantomGhost", "LocoTiger",
    "TropaDragon", "BrozTiger", "FiestaPinoy", "OmegaGhost", "NightDragon", "ChaosZero",
    "ShadowBrujoX", "ElBestia", "SavageBeast", "DarkBruh", "TropaFiesta", "WildGhost",
    "TurboLegend", "KalyeWarrior", "MegaCrow", "FiestaZero", "BarrioSavage", "PhantomZero",
    "RebelGhost", "LaSombra", "InfernoBeast", "BoomSavage", "WildBruh", "ShadowFiesta",
    "BrozDragon", "OmegaTiger", "SavagePinoy", "TurboSavageX", "KalyeZero", "DarkLegend",
    "FiestaBrujo", "BarrioDragon", "TropaLegend", "ChaosSavage", "MegaLegend", "MysticZero",
    "PhantomBrujo", "WildLegend", "LaTropa", "InfernoGhost", "TurboCrowX", "ElAzul", 
    "aksel", "astrid", "bergen", "bram", "casper", "daan", "elsa", "finn", "greta", "henrik",
    "ida", "jens", "karin", "lennart", "monika", "niklas", "olaf", "petra", "ralf", "sven",
    "thor", "ulrik", "vera", "willem", "ylva", "axel", "birgit", "claus", "diana", "emil",
    "felix", "gunter", "helene", "ilse", "jonas", "katrin", "lukas", "marta", "nora", "otto",
    "rolf", "sabine", "tomas", "ursula", "viktor", "werner", "yosef", "zander", "adelaide",
    "bruno", "conrad", "diego", "eduardo", "felipe", "gabriel", "hugo", "isabel", "jorge",
    "carmen", "lorenzo", "mateo", "natalia", "pablo", "ricardo", "santiago", "teresa", "valentina",
    "andrei", "bogdan", "cosmin", "dan", "eugenia", "florin", "george", "horia", "ion",
    "jana", "kristian", "lucia", "manuel", "nina", "oliver", "paula", "rafael", "simone",
    "theo", "uliana", "vadim", "xavier", "yolanda", "adrian", "beatrice", "cecilia", "dominik",
    "eliza", "fabian", "giulia", "hector", "iris", "julian", "kristina", "lucas", "marina",
    "nikita", "oscar", "patrizia", "roman", "silvana", "tobias", "una", "vlad", "winston",
    "alessio", "beatrix", "cesar", "daniela", "elias", "francesca", "giorgio", "hendrik",
    "ignacio", "jacek", "klaudia", "leopold", "magdalena", "nicolai", "octavia", "primo",
    "regina", "stefano", "tatiana", "umberto", "violeta", "wolfram", "yasmin", "zenon",
    "alonso", "benito", "cristian", "denise", "ernesto", "fernando", "gloria", "hidalgo",
    "ignatius", "joaquin", "kasper", "lidia", "marcelo", "noelia", "orlando", "patricia",
    "quirino", "roberto", "salvador", "trinidad", "ulises", "vicente", "xiomara", "yesenia",
    "armando", "blanca", "carlos", "dolores", "enrique", "fatima", "gerardo", "herminia",
    "isidro", "josefina", "lorenzo", "mercedes", "nestor", "ofelia", "pedro", "ramona",
     "TunnelRush", "HeavenSmoke", "SiteExec", "RetakePro", "ClutchMaster",
    "Sn1perWolfYT", "xXProGamerXx", "TTV_Destroyer", "YT_LegendKill", "Twitch_AceKing",
    "iSniperGod", "oProElite", "FaZe_Wannabe", "OpTic_Clone", "TSM_Reject",
    "NotToxic", "CarryOrInt", "OneMoreGame", "TiltProof", "RQKing",
    "AFKMaster", "LagGodMode", "PingIssue", "TeamBlamer", "AllMuted",
    "FeedMachine", "KSArtist", "SoloQHell", "RankAnxiety", "MMRClimber",
    "BoostMePlz", "SmurfAccount", "MainAccount", "BannedBefore", "ToxicClean",
    "TryHardMode", "CasualPlayer", "RankedGrinder", "UnrankedHero", "DuoQueue",
    "FullStackTeam", "PreMadeSquad", "SoloWarrior", "FlexPlayer", "OTPMain",
    "MetaSlave", "OffMetaGod", "PatchAbuser", "NerfSurvivor", "BuffedMain",
    "FirstBlood", "LastManStand", "TeamWiper", "SquadElim", "SoloWin",
    "TopFragger", "BottomFrag", "MidTable", "MVPStealer", "ACECollector",
    "PentaKiller", "QuadraFeed", "TripleKill", "DoubleKill", "ShutdownKing",
    "CombackKid", "NeverSurrender", "FF15Vote", "ReportJungler", "SupportMain",
    "ADCMain", "MidOrFeed", "TopOrTroll", "JungleGap", "RoleStolen",
    "AutoFilled", "OffRoleGod", "OneKickMain", "ChampPool1", "VersatileGod",
    "MechanicsOnly", "GameSenseZero", "MapAware", "BlindPeek", "SoundCue",
    "PreFireKing", "WallBang", "FlickShot", "TrackingGod", "SprayControl",
    "RecoilMaster", "CrosshairPlace", "UtilGod", "EntryFragger", "Lurker",
    "IGLMind", "SupportRole", "StatsGod", "WinRateLow", "KDAPlayer"
    
]
